---
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  EnvironmentName:
    Description: Define the work environment
    Type: String
    AllowedValues:
     - Development
     - Production
Conditions:
 CreateProdResources: !Equals [ !Ref EnvironmentName, Production ]

Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-6869aa05
    us-west-2:
      HVM64: ami-7172b611
    us-west-1:
      HVM64: ami-31490d51
    eu-west-1:
      HVM64: ami-f9dd458a
    eu-central-1:
      HVM64: ami-ea26ce85
    ap-northeast-1:
      HVM64: ami-374db956
    ap-northeast-2:
      HVM64: ami-2b408b45
    ap-southeast-1:
      HVM64: ami-a59b49c6
    ap-southeast-2:
      HVM64: ami-dc361ebf
    ap-south-1:
      HVM64: ami-ffbdd790
    us-east-2:
      HVM64: ami-f6035893
    sa-east-1:
      HVM64: ami-6dd04501
    cn-north-1:
      HVM64: ami-8e6aa0e3
  EnvironmentToInstanceType:
   Development:
    Type: t2.small
   Production:
    Type: t2.micro

Resources:
  MySG1:
   Type: AWS::EC2::SecurityGroup
   Properties: 
     GroupDescription: Lets create a web SG to allow traffic on port 80
     SecurityGroupIngress: 
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
     VpcId: !ImportValue MyVPC
  MySG2:
   Type: AWS::EC2::SecurityGroup
   Properties: 
     GroupDescription: Lets create a SG to allow ssh connection
     SecurityGroupIngress: 
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
     VpcId: !ImportValue MyVPC
     
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
        KeyName: !Ref KeyName
        #Specify the name of the SecurityGroups for EC2-Classic, default VPC. Otherwise use SecurityGroupIds
        SecurityGroupIds:
         - !Ref MySG1
         - !Ref MySG2
        ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64]
        InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref EnvironmentName, Type]
        UserData:
         Fn::Base64: |
          #!/bin/bash
           yum update -y
           yum install -y httpd24 php56 mysql55-server php56-mysqlnd
           service httpd start
           chkconfig httpd on
           groupadd www
           usermod -a -G www ec2-user
           chown -R root:www /var/www
           chmod 2775 /var/www
           find /var/www -type d -exec chmod 2775 {} +
           find /var/www -type f -exec chmod 0664 {} +
           echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
        #There is no option to specify VpcId, instead use SubnetId
        SubnetId: !ImportValue MySubnet
        #For a nondefault VPC, you must use security group IDs instead.
        #Image-id is conditional
  EC2Volume:
   Type: "AWS::EC2::Volume"
   Condition: CreateProdResources
   Properties:
    Size: 20
    AvailabilityZone: 
     !GetAtt MyEC2.AvailabilityZone
  EC2toVolumeMapping:
   Type: "AWS::EC2::VolumeAttachment"
   Condition: CreateProdResources
   Properties:
    InstanceId:
     !Ref MyEC2
    VolumeId:
     !Ref EC2Volume
    Dec: /dev/sdh
   
  MyEIP:
    Type: AWS::EC2::EIP
    Properties: 
        InstanceId: !Ref MyEC2
Outputs:
 EC2:
  Description: EC2 Instance Id
  Value:
   !Ref MyEC2
  Export:
   Name: EC2
 SG1:
  Description: MySG-1
  Value:
   !Ref MySG1
  Export:
   Name: SG1
 Volume:
  Condition: CreateProdResources
  Description: EC2 Volume
  Value: !Ref EC2Volume
  Export:
   Name: Volume
   

      
        